backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Translation"
        name: "config"
        file: "_data/translations.json"
        fields:
          - {label: Language, name: language_name, widget: string}
          - {label: Car, name: language_car, widget: string}
          - {label: Boat, name: language_boat, widget: string}
          - {label: House, name: language_house, widget: string}
          - {label: Street, name: language_street, widget: string}

