backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Map Configuration"
        name: "config"
        file: "_data/config.json"
        fields:
          - {label: Zoom, name: zoom, widget: string}
          - {label: Lng, name: lng, widget: string}
          - {label: Lat, name: lat, widget: string}
          - {label: Bbox, name: bbox, widget: string}

